### ISSUE TITLE
Not really an issue, just can't find your contact. Please, help me

### ISSUE THREAD

**Issue by mikhail-putilov** [nlloyd/SubliminalCollaborator#34]
Really, I dunno how to contact nlloyd personally. Sorry for that.

I'm trying to use twisted endpoints in my sublime plugin (it's just my for fun project). And I got stuck (see pic below). I can't figure out how didn't you stuck in the same place as I.
I tried to install pywin32 on embedded python with no luck.
Should I just remove endpoints dependency in my project? i think that's not the option cause I wouldn't be sure that another part of twisted framework uses win32api.
![image](https://cloud.githubusercontent.com/assets/699726/5703853/7f0d8512-9a8d-11e4-8ebe-38a1e7f27a18.png)

**Comment by nlloyd** [comment]
You may need to adjust in the plugin code the packages paths so that win32api can be found for the plugin. I don't know how you installed it into the embedded version but this is what has worked for me.
See https://github.com/nlloyd/SubliminalCollaborator/blob/master/commands.py lines 29-33.
Good luck!

**Comment by mikhail-putilov** [comment]
Yeah. I got it.
The reason why twisted raised the exception was importing endpoints.py
My code don't use IOEndpoint class, so I manually removed endpoints' dependence on stdio.py and everything works just fine. :)
Thank you.
